movietask2/credentials/urls.py
from django.urls import path, include


from credentials import views
app_name='credentials'

urlpatterns = [

   path('register/',views.register,name='register'),
   path('login/',views.login,name='login'),
   path('logout/',views.logout,name='logout'),
   path('moviepage/',views.moviepage,name='moviepage'),
   path('profile/', views.profile, name='profile'),
   path('save_profile/',views.save_profile, name='save_profile')
]

movietask2/movie/urls.py
from django.urls import path, include

from movie import views

app_name='movie'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('movie/<slug:c_slug>/', views.allmoviecat, name='movies_by_category'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('moviepage/', views.movie_show, name='movie_show'),
    path('allmovies/<slug:c_slug>/', views.allmoviecat, name='allmoviecat'),
    path('add/', views.add_movie, name='add_movie'),


]

movietask2/movietask2/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie.urls')),
    path('',include('credentials.urls')),
    path('',include('searchapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movietask2/searchapp/urls.py
from django.urls import path


from . import views

app_name = 'searchapp'

urlpatterns = [
    path(' ', views. searchresult, name='searchresult')]

movietask2/templates/add.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="desc" placeholder="enter movie description"><br>
    <input type="text" name="date" placeholder="enter movie release year"><br>
    <input type="file" name="img"><br>
     <input type="text" name="category" placeholder="enter category name"><br>
    <input type="submit"><br>

</form>

movietask2/templates/category.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Title</title>
</head>
<body>
   {% include 'navbar.html' %}
    {% if category %}
        <div class="container-fluid">
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p> <a href="{% url 'movie:allmoviecat' category.slug %}">Movie Categories</a> </p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="container">
        <div class="row">
            {% for movie in movies.object_list %}
                <div class="my-bottom-margin col-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="card text-center">
                        <img class="card-img-top" src="{{ movie.img.url }}" alt="Card image cap" height="250px">
                        <div class="card-body" style="height:600px;">
                            <h4 class="card-title">{{movie.name}}</h4>
                            <p class="card-content">{{movie.desc}}</p>
                            <a href="{% url 'movie:detail' movie.id %}" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if movies.paginator.num_pages %}
            <hr>
            <div class="text-center">
                {% for pg in movies.paginator.page_range %}
                 <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
</body>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

movietask2/templates/delete.html
<form method="POST">
    {% csrf_token %}
    ARE YOU SURE ?
    <input type="submit">
</form>

movietask2/templates/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIE WEB</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<div class="container-fluid">
    {% include 'navbar.html' %}
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.img.url }}" class="img-fluid rounded" alt="{{ movie.name }}">
        </div>
        <div class="col-md-6">
            <h1 class="display-4">{{ movie.name }}</h1>
            <div class="description-box bg-light p-3 rounded">
                <p class="lead">{{ movie.desc }}</p>
            </div>
            <p><strong>Release Date:</strong> {{ movie.date}}</p>
            <p><strong>Actors:</strong> {{ movie.actors }}</p>
            <p><strong>Category:</strong> {{ movie.category }}</p>
            <a href="{{ movie.youtube_link }}" class="btn btn-primary btn-lg mr-2" role="button">Watch on YouTube</a>
            <div class="d-inline-block mt-3">
                <a href="{% url 'movie:update' movie.id %}" class="btn btn-warning mr-2">Update</a>
                <a href="{% url 'movie:delete' id=movie.id %}" class="btn btn-danger">Delete</a>
            </div>

            <div>
                <h2>Reviews</h2>
                {% for review in reviews %}
                    <p>{{ review.rating }} - {{ review.review_text }}</p>
                {% empty %}
                    <p>No reviews yet.</p>
                {% endfor %}

                <h2>Add a Review</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit Review</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% include 'footer.html' %}

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movietask2/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movietask2/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
      margin: 0;
    }

    .content {
      flex: 1;
    }

    .footer {
      background-color: #f8f9fa;
      padding: 10px;
      text-align: center;
    }
  </style>
</head>
<body>

  <div class="content">
  </div>

  <footer class="footer">
    <p> & copy; MovieWeb .All rights reserved</p>
  </footer>
</body>
</html>

movietask2/templates/header.html
{% load static %}
<header style="background-color: black;">
    <center>
        <img alt="logoimage" src="{% static 'img\logomovie.png' %}" width="130px;">
    </center>
</header>

movietask2/templates/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="container-fluid">
    {% include 'header.html' %}
    <body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            ONLINE MOVIE SITE
        </a>
    </nav>
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <h2>Register Yourself</h2>
            <form method="POST" action="{% url 'credentials:register' %}">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Enter your username"><br>
                <input type="text" name="firstname" placeholder="Enter your firstname"><br>
                <input type="text" name="lastname" placeholder="Enter your lastname"><br>
                <input type="email" name="email" placeholder="Enter your email"><br>
                <input type="password" name="password" placeholder="Enter your password"><br>
                <input type="password" name="confirm_password" placeholder="Confirm password"><br>
                <input type="submit" value="Register">
            </form>
        </div>
        <div class="col-md-6">
            <h2>Login</h2>
            <form action="{% url 'credentials:login' %}" method="POST">
                {% csrf_token %}
               <input type="text" placeholder="Enter username" name="username"><br>
               <input type="password" placeholder="Enter password" name="password"><br>
               <input type="submit" value="Login">
            </form>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% elif message.tags == 'success' %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movietask2/templates/movie_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
    {% include 'navbar.html' %}
</div>

<h1>Movie List - {{ category_name }}</h1>  <!-- Display the category name -->
<div>
    <h2>Categories</h2>
    <ul>
        {% for category in categories %}
            <li><a href="{% url 'movie_list' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

<div class="container">
    <div class="row">
        {% for movie in movies %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top" src="{{ movie.img.url }}" alt="{{ movie.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie.name }}</h5>
                        <p class="card-text">{{ movie.desc }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

movietask2/templates/moviepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIE WEB</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<div class="container-fluid">
    {% include 'navbar.html' %}
</div>

<div class="container">
    <div class="row">
        {% for i in page_obj %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem; margin-bottom: 20px; height:900px; margin-top: 20px;">
                <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" height="250px">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">{{ i.desc }}</p>
                    <p class="card-text">{{ i.date }}</p>
                    <p class="card-text">{{ i.actors }}</p>
                    <a href="{{ i.youtube_link }}">Watch on YouTube</a>
                    <a href="{% url 'movie:detail' i.id %}" class="btn btn-primary">click here</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
   <div class="mx-auto">
    {% if page_obj.paginator.num_pages %}
    <hr>
    <div class="text-center">
        {% for pg in page_obj.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if page_obj.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

{% include 'footer.html' %}

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movietask2/templates/navbar.html
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-sm">
        <a class="navbar-brand" href="#">
            ONLINE MOVIE SITE
        </a>
        <li class="nav-item dropdown {% if 'movie' in request.path %} active {% endif %}">
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <ul>
                    <li><a class="dropdown-item" href="{% url 'movie:allmoviecat' 'default-slug' %}">All Movies</a></li>
                    {% for cat in links %}
                    <li><a class="dropdown-item" href="{{ cat.get_url }}">{{cat.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </li>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="mx-auto" style="padding-right:100px;">
      <form class="form-inline my-2 my-lg-0" role="search" action="{% url 'searchapp:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success float-right" type="submit"><i class="fa-brands fa-searchengine"></i>Search</button>
      </form>
      </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="index.html">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:profile' %}">Welcome, {{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'credentials:login' %}">Login</a>
                </li>
                {% endif %}
                 <a href="{% url 'movie:add_movie' %}" class="btn btn-light" style="float:right; color:black;">Add movie</a>
            </ul>
        </div>
    </nav>
</body>

movietask2/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Profile</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    {% include 'header.html' %}
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">ONLINE MOVIE SITE</a>
         <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'credentials:moviepage' %}" style="color: black; background-color: white;">Movies</a>
            </li>
        </ul>
    </nav>
    <div class="container mt-4">
        <div class="card">
            <div class="card-header bg-primary text-white">User Profile</div>
            <div class="card-body">
                <form id="profile-form" method="POST" action="{% url 'credentials:save_profile' %}">
                    <div class="form-group">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}" readonly>
                    </div>
                    <button type="button" class="btn btn-primary" id="edit-btn">Edit</button>
                    <button type="button" class="btn btn-success" id="save-btn" style="display: none;">Save</button>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>

    <!-- Script to enable edit functionality -->
    <script>
        document.getElementById('edit-btn').addEventListener('click', function() {
            document.getElementById('username').readOnly = false;
            document.getElementById('email').readOnly = false;
            this.style.display = 'none';
            document.getElementById('save-btn').style.display = 'inline-block';
        });

        document.getElementById('save-btn').addEventListener('click', function() {
            var form = document.getElementById('profile-form');
            form.submit();
        });
    </script>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movietask2/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Search</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        main {
            flex: 1;
        }
    </style>
</head>
<body>
{% include 'navbar.html' %}
<main>
    <div>
        <p class="text-center my-search-text">You Have Searched for: <b>"{{query}}"</b></p>
    </div>
    <div class="container-fluid">
        <div class="row">
            {% for movie in movies %}
                <div class="my-bottom-margin col-12 col-sm-6 col-md-4 col-lg-4">
                    <div class="card text-center" style="width: 20rem;">
                        <a href="{{movie.get_url}}">
                            <img class="card-img-top my_image" src="{{movie.img.url}}" alt="{{movie.name}}">
                        </a>
                        <div class="card-body" style="width:20rem;">
                            <h4>{{movie.name}}</h4>
                            <p>{{movie.desc}}</p>
                             <a href="{% url 'movie:detail' movie.id %}" class="btn btn-primary">click here</a>
                        </div>
                    </div>
                </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center my-search-text">0 Result Found</p>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% include 'footer.html' %}

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>